name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The CMake configure and build commands are platform-agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt update && sudo apt install -y clang unzip cmake lz4 python3 git mercurial

      - name: Install Python Dependencies
        run: pip install certifi

      - name: Build Packages
        run: ./build_linux.sh

      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: packaged/